


                  /////////THE DAILY INSPIRATIONAL MESSAGE/////////
//The daily inspirational message.
var daily_quotes = [
 "Hi  don't forget to smile ",
 "You are beautifully made ",
 "You are the best gift ",
  "Hi  I just wanted you to know that you are one of a kind",
 "Good morning  I just want to remind you that you are a very special person. Don't ever forget ",
  "Good morning  just a reminder that you are an amazing ",
  "Dear  I just want you to know that you are not ",
  "You are loved  don't ever forget ",
   "You are unique ",
 "DearI just want you to know that you are perfect the way you are", 
 "Don't get all worked up  remember every day is a new chance to make things right, Good morning",
  "Dear  you are incredible.",
  "Good morning  just a reminder that you are a bright shining star",
  "Dear  I just want you to know that someone cares",
  "Dear  I just want you to know that you've got the key to your happiness, you just have to believe in yourself",
  "Today is going to be a good day  just believe",
     "You are a wonderful person ",
   "Don't give up  you will conquer",
  "Don't feel bad if it doesn't go as planned  just try again”, 20. “You will make it to the top (name of user), keep working hard",
   "You are a winner  don't let anyone convince you that you are a loser”,  22. “You are a survivor (name of user)",
  "Don't get all worked up  you will definitely e your ",
   "Nothing is impossible if you believe in yourself ",
     "Dear  I just want you to know that you will never be alone no matter the situation you find yourself”,  26. “Dear(name of user), it doesn't matter what others think of you. Just know that you are perfect the way you ",
  "Dear  it's okay to make mistakes. It doesn't make you a bad person. Mistakes are part of the lessons of ",
  " don't feel bad if you don't get it right the first time, just try ",
  " You are a champion  so keep going, I've got your back", 
  "You can make it to the top  it doesn't matter where you are, who you are and what you have been through. You just have to believe in yourself",
 "Believe in yourself  you can do ",  
 "It's going to be alright   don't be so hard on ",  
  "Life is worth living ",
 "Don't let what others do to you, change you into a bad person",
    "You are strong  keep pushing",
   "I believe in  you can do ",
 "You are not alone ",
 "You can do it!",
 "You are a bright shining light  don't let what anyone says dim your ",
 "You have all it takes to achieve your dreams",
  "You are stronger than you know ",
  "Have faith, it will be over",
  "You are going to make it, keep working hard and chasing your ", 
   "You are amazing , don't let anyone tear you ",
   "You can be anything you want to be, don't let anyone discourage ",   
    "Love yourself always, no matter the changes you go ",
   "Dear, I know sometimes things get tough and doesn't always go as planned, but that doesn't mean you should give up, just keep trying.",
  "You are perfect even with all your scars ",
  "Dear  don't forget to love yourself even if others don'",
 "Don't let anyone love you more than you love yourself ",
  "Dear, you could be that someone treating you ", 
   "You have all the talent and strength to achieve your dreams",
   "Dear , other people's views about you don't matter",
  "Everyday is a new beginning ",
"Dear , I know it has been tough but just take a deep breath, smile and keep ",
 "Dear , if what you do , doesn't bring you happiness, let go of it and go for what makes you ", 
  "I know sometimes it's hard, but I want you to know that I believe in ",
   "Don't worry , it's okay to feel bad sometimes, it's part of the challenges of ",
  "Don't give up if you fail, remember failure helps us to grow and learn from our ",
  "Always remember that, I'm here for you even if things get ",
  "It may be difficult to find the positivity amongst the problems you find yourself but it will make a whole lot sense when you ",
  "Dear , you are worth so ",
 "Believe in yourself  and every day will be the best day of your ", 
 "If it doesn't work out the first time, take a deep breath, smile and try ",   
 "It's okay to cry, it makes you human",   
 "Be kinder to yourself  imagine how you would feel if you treat yourself the way you treat your best friend",
 "You are the perfect definition of amazing",
 "Be happy and proud of the amazing, unique features that make you, ",
  "You are worth much more than you know ",     
 "You are priceless ",
   "Investing in your happiness doesn't make you a selfish person ",
     "Be confident in yourself always ",
 "Don't forget to love yourself ",
     "Don't stress yourself trying to change other people's opinions about you, just keep being you and don't give a damn if others don't like ",
     "Love and embrace the person you are",
  "You are enough just the way you are ",
    "Love yourself ",
   "Be proud of who you are ",
  "Hey  I just found the most amazing, unique and beautiful person in the world, if you wanna know the person just take a look at the mirror. That person in the mirror is the most amazing, unique and beautiful person in the ",
   "Stop underestimating yourself, you can do it.",     
    "You are a masterpiece   the best of all.",
    "You deserve your love and attention more than any other person in the world",
     "You are powerful ",
   "You are loved",
"You have value ",
    "Calm down and cheer up  everything is going to be ",   
    "Don't forget to put yourself at the number one spot of your to do ",
    "Stop trying to change yourself to please anyone. You were made to be you",
      "You don't need to be perfect to inspire others",
   "Dear  don't let anyone tell you that you are worthless because you have ", 
     "Never give up on yourself ",
     "Never give up on your dreams",
       "You are an exceptional work of God ",    
        "You don't have to be perfect to be ",
     "Only the opinion you have about yourself ",
 "on't let what you see in the internet, make you feel bad about your, most things on the internet are ", 
   "Trust your ",
  "You don't need others approval to be happy",
     "You are better than you think ",     
      "You don't have to be perfect to be amazing ",
             "You are more beautiful when you decide to be yourself ",     
  "You are worth it", 
 "You have the capabilities to achieve your dreams ",      
 "You are your own kind of beautiful ",
    "Dear  you, you matter ",  
    "Always forgive yourself when you make mistakes ",
          "It's okay if you struggle to accept love ",
 "DearDear each time you feel angry, take a deep breath, rest and ask yourself if it's really worth your ",
     "Don't forget to thank God for creating an amazing person like you ", 
       "Don't let anyone define who you should be, because you are the best of who you are meant to be",
    "To be beautiful means to  be ",
   "Don't worry about what others will say, because even the smallest act of kindness would make a big ",
    "Don't let anyone define who you ",
      "Your life is yours  and it's the best gift you have in this world, don't let anyone ruin ",    
         "Self love is the key to happiness",    
          "Appreciate yourself , you did your ",
 "Be proud, you are different Your difference makes you beautiful and ",
 "Taking care of yourself and loving yourself doesn't make you a selfish person ",
    "Value yourself because you are priceless",
    "Don't forget to complement yourself even if no one does",
   "Always celebrate your little achievements ",
    "Accept yourself the way you are ",    
    "Believe in yourself you are good ",
       "Always have a strong positive self image of yourself ",    
 "You don't need others approval to be happy",
  "Always be self compassionate",
  "Because others don't appreciate you doesn't mean you are not good enough ",
 "Don't try to please others at the expense of your own happiness ",
   "Dear , don't forget to love yourself first before loving ",
   "Loving yourself is the first secret to happiness ",     
  "Dear  you are amazing with all your ",    
    "love yourself unconditionally",  
      "Be happy with yourself , just the way you ",
    "Dear  you, you matter ",   
      "I can't imagine the world without you , you are so important to the ",
       "he greatest gift you have in the world is you",
    "You are meant to shine  and you will ",   
   "Other people's opinions don't matter ",
      "You have the right to be yourself it's your ",
  "The only thing that matters is what lies inside your heart ",   
  "Try living yourself today ",
       "Loving yourself means no one's opinion matters when it comes to take positive care of ",
     "It's okay to make mistakes ",
   "It's okay not to be okay ",      
  "Be your own kind of beautiful ",    
  "it's okay to do what you think is best for you",
    "You are ",
    "You deserve a beautiful life ",
     "You are much braver than you know ",   
 "You got this  you can do ",
    "Today is the perfect time to be ",
    "Do the positive things you love and don't let anyone discourage ",
     "Of course life is tough but so are ",
 "You are unstoppable ",     
 "Be brave you have got ",      
 "Just take a deep breath and give it another go",    
 "Don't let what others think or say about you destroy your inner peace ",    
 "Happiness is the best kind of cool ",   
   "Deardon't stress yourself over the things you can't change or ",    
    "Never stop believing in yourself ",    
      "Today is going to be a fabulous day just ",    
 "You have the power to change the world and make a difference ",
    "Don't forget to start each day with a prayer and a grateful heart ",    
 "Be yourself. It doesn't matter if other people don't like ",    
 "Embrace what makes you different",
 "Strength comes from doing the things, you thought you couldn't do",       
  "Dear, don't forget to thank God for making you, ",      
 "Be thankful for the little things that make you, you ",       
 "God is with you always",    
"Stop putting yourself down by trying to please everyone ",      
 "It's okay to cry  some days are harder than ",     
 "People bully you because they are intimidated by the light you radiate",     
  "Be that person who always shows up and never gives up ",       
   "Be that person who believes that everything is possible and works for it",
  "Take a deep breath and have faith , what is meant for you will surely get to ",      
"Why be sad, when you can choose to be happy ",
 "You can choose to be angry and moody or you can choose to let go of that makes you sad and be happy. It's your choice",    
  "Why be moody when you can shake your booty !",       
   "Always stand tall and proud of who you are ",     
  "Embrace positivity",    
  "Keep smiling",     
    "Don't forget to laugh out loud today",    
     "Today is going to be a great day , so be happy",     
  "You are more beautiful when you smile ",        
 "The secret to prevent aging is so easy, just ",       
"You are a beauty to behold ",   
 "You are just like a diamond , only you can bring yourself ",
  "You are much smarter than you think ",    
  "You are strong ",    
  "You are awesome ",    
    "Dear , just a reminder that you are the most amazing person ",   
    "You are a breathtaking work of art ",   
  "You are blessed ",    
  "Dear, don't ever think of taking your life because you are precious to me and God (name of user)",     
     "Suicide is never an option", 
    "face your fears , it makes you stronger",        
     "Do something positive today",  
 "You are destined to be a star ",      
  "You are a blessing to the world ",      
  "You are loved ",
  "You have the power to change the world ",      
  "You are a priceless gift",
    "You are as precious as the air, can't imagine the world without you",         
     "Put a smile on someone's face today, Good morning",        
     "Let love lead in everything you do ",       
     "Put a smile on someone's face today",   
 "Everyday is a new opportunity to start afresh ",     
 "You have the potentials to achieve your goals",   
"You can always outgrow toxic friends and relationships ",      
 "You are more precious than gold ",     
"You don't have to be rich to touch lives ", 
 "God loves us all despite our differences ",    
 "A little smile on your face can brighten the day of those around you",    
  "You don't have to prove yourself to anyone you are good enough just the way you ",
  "What others say about you don't matter ",     
 "You are an inspiration to the world",
 "You have the strength and power to prove them wrong ",     
  "No matter the situation, you find yourself, never forget to thank God. Good ",      
 "You are one of God's finest blessings ",        
  "Being yourself is the best kind of cool ",        
  "You are all shades of awesome ",      
   "You are a wonderful person ",    
   "You are much better than you think ",       
     "You are an amazing gift of God ",       
      "Don't ever accept anybody's definition of your life ", 
     "Always make room for the positive things that make you happy ",       
 "Loving yourself is the secret to happiness and long life ",       
  "Don't rely on anyone for your happiness and self ",
 "Your past doesn't define you",     
  "Everyday is a new day and a new chance to rewrite your story",    
 "You were born an original , you don't have to be like anyone to be happy",     
 "You are never too old to chase your dreams ",    
  "Today, you are you and that's is the best gift of all ",      
 "The secret to a healthy living is self love",      
  "You are capable of so much",    
   "You have everything you need to achieve greatness ",       
  "Always stand firm for the positive things you believe in ",     
   "There is no better you than the person you are ",      
    "You get better every single day ",
 "Don't feel so worked up , all your problems have solutions",      
 "Don't feel bad for making mistakes mistakes help you learn and grow",      
 "No mistake is beyond forgiveness. Forgive yourself always ",       
 "It's okay not to know it all",    
"Choose to think positive today",  
 "You can achieve anything if you put your mind in it",       
"You can always do better next time ",      
 "It's okay to get wrong the 20th time ",        
  "You are free to make your own decisions, don't let peer pressure or bullies push you into taking the wrong decision",     
  "Suicide is never an option ",    
 "You can make a difference",    
 "Be confident in yourself ",
  "You are in charge of your life ",  
  " Believe in your abilities ",    
 "Disability is not an excuse, you have all it takes to achieve your dreams",    
"You have the power to make your dreams come alive ",     
 "Everyday is a new chance to start afresh",   
 "Good things are coming your way ",      
"God loves you" ,    
 "Having positive thoughts is the best way to be happy, so why don't you try it",     
 "If you fall, don't give up, just dust yourself and keep moving ",     
 "Your confidence starts when you step out of your comfort zone",   
 "Most times things aren't as bad as you think they are ",        
 "Do the positive things that make you happy ",
 "You are whole ",       
 "Stop ruining your self esteem by comparing yourself to others, you are good enough the way you are",      
 "Just do your best ",       
  "Accept yourself the way you are ",    
  "Be content with yourself",   
  "Today is going to be an awesome day ",     
"You are lovable ",   
  "Trust that tiny positive voice in your heart ",      
 "You belong ",      
  "You deserve to be happy ",     
 "You bring joy to the world ",      
  "You own this, so don't give up ",     
   "You will get through the hard imes , you just have to believe in yourself",   
   "You are talented and intelligent ",
  "You don't have to worry about the things, you can't control ",      
 "Your past has no power over your future",      
  "Don't allow the fear of failure stop you from chasing your dreams ",     
  "Find happiness, even in the smallest places ",    
   "You are in charge of how you feel ",    
  "Use your position to be an inspiration to others ",       
   "Be optimistic about yourself and your future",    
  "Your mistakes don't define you",      
 "You are the only person who can define you ",
  "Your past doesn't define you ",    
    "You are one of a kind ",
 "Today is a blessing",  
  "Your potential is limitless",
  "Be fearless", 
  "You have everything to be grateful for",   
  "Stop criticizing yourself",   
"Stop comparing yourself to the people you see on the internet",   
 "You can do it",  
   "Today let go of everything that makes you sad",
 "Speak out if you are being bullied",
   "Suicide is never an option",    
   "Be proud of yourself",     
 "You are brave, bold and beautiful",    
 "Give God a chance",    
"The little steps you take matter",
"You are stronger than that mean voice trying to bring you down", 
 "Happiness is a choice, so choose to be happy",  
 "Live today to it's ",   
 "Be thankful for your ",   
"You are gorgeous and ",   
 "Spread love and radiate happiness everywhere you ",  
 "Love God ",   
 "Today is a new day, don't let what happened yesterday ruin today for ",  
 "You are not a ",  
 "You were created for a "

];

  
                            //////////////////////////THE 100 BIRTHDAY MESSAGE///////////
             //The 100 birthday messages

var birthday_quotes = [
 "You work so hard and give so much to others. May this year be filled with many doors opening to you, and may you reach your biggest goals. Everything you have ever wanted is waiting for you to come and take it. Happy birthday!",
"May your birthday balloons be as big as your dreams, and may they both soar to brand new heights. Happy birthday!",
"May the stars light the path to all your hopes and desires. Fly, run, walk, crawl. Endure. If you want it, it will happen. Happy birthday!",
"Just be yourself and keep moving forward. You have the power to make your dreams happen. You are almost there. Take some time to celebrate the extraordinary day it must have been when you were born. Happy birthday!",
"This will be the year that all of your hard work pays off. Remember always that you are incredible…and stronger than you can ever imagine. I believe in you! Happy birthday!",
"It is time to celebrate you! You are amazing. Happy birthday!",
"You have so much talent and grit that I know you can do anything. Conquer first the lake, then the sea, then the ocean. Dare to achieve great things! Happy birthday!",
"You’ve worked so hard. You’ve sacrificed. You’ve been fearless and have shown unwavering commitment. You are unstoppable and I hope on this important day you can take some time to look back at your life and feel a profound sense of accomplishment and pride in yourself. I certainly see it. Happy birthday!",
"As you enter a brand new year, I hope that you feel just how loved and cherished you are. My wish for you is that all of your goals are realized and then that you make even bigger goals to conquer. You are a rockstar. Never forget that. Happy birthday!",
"May this be the year you dare to do things that scare you. Pull out your sword and conquer dragons. Show everyone what you are made of. Happy birthday!",
 "Happy Birthday! I hope that you continue to trust the process, and believe that nothing is ever truly impossible. You are capable of more than you could ever imagine, and with the right mindset, absolutely anything can be achieved. Never give up, and never stop dreaming! Enjoy!",
"With every year that passes, remember that you are becoming stronger, wiser and more compassionate! Happy birthday to someone who never stops dreaming and who never loses hope for the future. Remember that the best is yet to come!",
"Happy birthday to a truly extraordinary person! Keep aiming for greatness and you won’t fail. Believe in your dreams for the future!",
 "It’s time to celebrate a brand new year and a brand new you! This will be the year that big things happen for you. Remember: You’ve got this. Happy ",
 "This year, may you be rewarded with more success, laughter, joy, and hope. Now and always,. Happy ",
"Believe in yourself, and you will see what I have always seen in you. Happy birthday. May this year be filled with new and wonderful things.",
"Keep turning every challenge you face into an amazing opportunity. Stay strong! Happy ",
 "Happy birthday! This will be the year that you accomplish even more fantastic things. Happy ",
" Sending the warmest birthday wishes to a one-of-a-kind human being! You have so much potential, and so much more to offer to the world. Keep striving towards greatness and never look back. I hope that you never lose sight of your inner purpose and strength! You’ve got this! Enjoy your day – you’ve earned it. Happy birthday!",
"As you enter a new year and new chapter of your life, may you feel the love and support of all those around you, and may wonderful opportunities await you. Happy birthday!",
"Happy birthday to a fantastic, one-of-kind person. You have so much ambition, and never be afraid to reach for the stars. This year, may all your wishes come true.",
"You deserve the very best life has to offer. May this year bring forth amazing things for you. Happy birthday!",
"Nothing can stop you from reaching your dreams this year. Happy birthday.",
"Wishing you a year filled with prosperity, success, and all the incredible things your heart can hold. Happy birthday.",
"You are an amazing force in this world. You can do anything you set your mind to, and your talent has no limits. May this year be filled with special things for you. Happy birthday.",
"Happy birthday, to a strong, smart, incredibly wonderful person. This year, may all your hopes and desires come true, and may all of your hard work pay off.",
"Wishing you a happy birthday. May all of your dreams come true this year. Never forget that you can do anything you set your mind to",
"our ambition has no limits, and your talent is boundless. May this be the year that all of your hopes and desires come true. Happy birthday!",
"As you enter a brand new year, may your path be filled with new opportunities to reach for, and new goals to achieve. So proud of you, today and always. Happy birthday!",
"When you believe in yourself, incredible things happen. Wishing you a very happy birthday. May this year be filled with incredible things",
 "Live each day with love, grace, and gratitude. Remember that you can do anything and that you are so very loved. Happy birthday",
" Happy birthday to unique, , so wonderfully beautiful YOU",
"You are beautiful, capable, and stronger than you know. You have got wonderful talents and an incredible soul. Happy birthday!",
 "Here’s to a year of big hopes, wonderfully outrageous desires, and great opportunity! You can do anything. You’re awesome,  Happy birthday!",
 "Happy birthday to the strongest, smartest, funniest person I know. This year will bring all the great things you deserve.",
"Today and always, remember that you are so very loved and that you have the power to make all of your dreams a reality. Happy birthday!",
"Wishing you the happiest birthday. This year, reach for the stars, work hard, and may all of your dreams come true",
"May the sun always be bright in your sky, and may the stars light the way for all of your hopes and desires to come true. Happy birthday",
"You are wonderful, brilliant, and you fill each day with joy. Happy birthday, and may all your wishes come true",
"It’s time to celebrate another year around the sun! Remember always that you are amazing, smart and more than capable to kick the butt of any task or project! Happy birthday",
"You’re this age only once, so make the best of it. Live your life like nobody’s watching! Happy birthday!",
"Today could be the start of something special! Enjoy every second of your birthday! Then, carry that joy in your pocket like spare change (so it will be there when you need it)!",
"May life take you on a journey you never imagined, bringing you to a destination that stirs your soul, gives you peace of mind and surrounds you with love! Happy birthday!",
"You’re a total original! Never a follower. Always a leader. You are an amazing trailblazer! Don’t you ever forget it! Happy birthday!",
"Happy birthday! At your age, you have so much to experience, and what an experience it will be.",
"Happy birthday! I know you will have the greatest of special days, a great year and an even greater lifetime.",
"Happy birthday! Your age is no reflection of who you are or what you’re capable of. It’s only the age of the machine that houses what really defines you: your kind heart and soul",
"Happy birthday! How old or young you are has nothing to do with who you really are. Age is a testament to how much you’ve lived, and you’ve lived well",
"Happy birthday. You still have so much more to explore. May your journey take you to where you want to be",
"Happy birthday. The path ahead may seem full of uncertainty, but every bend brings a different view — mostly magnificent. Like you.",
"Happy birthday. Life on Earth is a gift. Take it out, live it and share it. You’ll be rewarded with even greater gifts",
"Happy birthday. Today is wonderfully a milestone that marks where you’ve been and where you have left to go. May you keep surpassing every milestone down the road",
"Happy birthday. With every birthday, you become a little wiser and happier. In time, you’ll be so wise that happiness will be as natural as opening your eyes in the morning. You’ll see.",
"Happy birthday! In time, you will achieve great things. This I know. What’s left is for you to find out yoursellove",
"Happy birthday! You are great. You have great talent. You have great gifts. You are greatly loved",
"Happy birthday! Nobody compares to you. You’re truly a unique soul. And you  shine brighter with every birthday you’re blessed to have.",
"Happy birthday! You are a wonderful example of what happens when someone is blessed with love, joy and wonder. May you always be blessed just so.",
"Happy birthday. May you never stop dreaming, for your dreams are what will take to the greatest heights. I know it.",
"Happy birthday. Your birthday is but a milestone you celebrate on the road to eternal joy and adventure. May you celebrate many more milestones.",
"Happy birthday. Make rainbows when it rains, so you can discover the pot of gold that ultimately awaits you in the sunshine",
"Happy birthday. Try to touch the sky. It doesn’t matter if you fail, just get up, dust yourself and keep moving",
"Happy birthday. May you spread your wings, soar higher than you ever imagined and shower this world with your beauty",
"Wishing you the heart, strength and foresight to see the incredible places your dreams will take you in the years to come!",
"Your cup has always “runneth” over. That’s what makes you special. Happy birthday",
"Happy birthday! May your dreams bring you bliss, unleashing everything beautiful that life has to offe",
"Happy birthday! You are an inspiration. That’s a wonderful gift you have",
"You have a brilliant gift. You shine. May you always beam a beautiful light for others to follow. Happy birthday",
"Happy birthday! Don’t think about the road traveled. Look forward to the byways and highways ahead. The best part of your journey is yet to come. Enjoy the ride and, every once and awhile, stop to enjoy the view",
"If you truly believe in yourself, everybody will believe in you too. I believe you have what it takes to succeed at anything. Happy birthday",
"Happy birthday! You’re a giant, so I know you have it in you to make great strides.",
"When your mind, heart and eyes are wide open, your dreams will come true. I know you have enough of a beautiful mind, kind heart and sharp eye to find your way to your bliss. Happy birthday!",
"Happy birthday! You have a brave heart. You have the courage to be who you are. Take flight! Birthdays are made for flights of fancy!",
"Throw away the sails on your birthday and let the winds of change take you into the unknown. Life is more of an adventure when you venture out of your comfort zone. Happy birthday!",
 "Stay brave, positive and upbeat every day — and let your hopes and dreams be your guide! Happy birthday!",
"A wonderful life awaits you. A life full of joy, love and prosperity. You have so much potential and truly deserve life’s best (even if you don’t think so). Happy birthday!",
"On your birthday, may you have the wind in your sails to stand up to life’s toughest storms and coast through every beautiful, sunny day. Happy birthday!",
"At your age, you begin to learn so much about true love and real joy. Rest assured you will have the time of your life discovering both of them. Happy birthday!",
"Hoping you grow up to be a wise person. You’re already a fabulous person. Stay as amazing as you are and keep making the world a better place. Happy birthday!",
"May all your dreams take flight when you’re ready to fly! This birthday could be the beginning of this journey! ",
"Every passing year brings new experiences and renewed hope for tomorrow. May you have an eternity of both. Happy birthday!",
"Happy birthday! You are truly special",
"Tomorrow can bring untold joy, love and peace of mind. Whatever your troubles, sleep on it! Happy birthday! Here’s to tomorrow!",
"May every year of your life bring you new friends, greater wisdom, renewed hope and just enough light to stir your soul, tame your demons and fan the flames of love. You deserve it! Happy birthday!",
"You may think your age is a giant number, but you have it all wrong — you’ve always been a giant in the lives of your loved ones! May you have a birthday as awesome as you are!",
"I am glad that the world has been blessed by an amazing person like you for so many years! You make every day brighter with your love and warmth! Happy birthday.",
 "Keep your beautiful smile, your boundless love of life and your relentless optimism. You light up every moment of the day. Happy birthday!",
"ff you are born with a talent, you were meant to use it in some way. This birthday, may you discover many more secret talents in yourself. Happy birthday!",
"Every birthday, decide to live wholeheartedly, as if it were your last birthday ever. Every birthday, learn more wholeheartedly, as if you never knew anything before. Happy birthday!",
"As you get older, have more dreams than memories, more opportunities than chances, more hard work than luck and more friends than acquaintances. May you have the very best in life. Happy birthday!",
"Do you want to look back in life and think about what a great life you’ve had? Always look ahead to the next adventure! Happy birthday!",
 "May each birthday you celebrate bestow upon you great things: like the confidence to chase after your dreams and the wisdom to chase after the right ones…starting with this birthday!",
 "When you look back at your life, like what you see? Don’t worry — you have many tomorrows to walk away from the past, reinvent yourself and start rebuilding for the future. I know you can. Happy birthday!",
 "On your birthday, we’re here to tell you that we will always back you in everything you do. Happy birthday!",
"You should have the wings of an angel. You’ve certainly earned them from all the lives you’ve touched and continue to touch in your special way. Hoping your birthday is truly your special day",
"As you travel through life, may you always have love, joy and success…and may you never look back with anger or regret. Happy birthday!",
"Counting your blessings and loved ones is a joy that very few have on their birthdays. May you always have happiness in your life. Happy birthday!",
"On your birthday, I wish you a year full of success and joy. With faith, courage and dedication, no dream is too big. Happy birthday.",
"Your birthday today is special because it marks your amazing journey you since birth and the beginning of many more new adventures and discoveries. Happy birthday", 
"If you think you’ve lived life fully until now, you know nothing. The best years of your life are yet to come. Live it up! Happy birthday!",
"Have you made many wishes? May all your wishes come true on your birthday and take off ever after. Happy birthday!",
"Your birthday is the perfect opportunity to take a break, look at everything around you, feel alive with all your heart and promise yourself to do great things. Happy birthday!"



];
 

////////////////////////////////////////////////SELF LOVE QUOTE//////////////////////////////////////////
//The 100 self love quotes
var self_love_quotes = [
"Who looks outside, dreams; who looks inside, awakes.",
"The better you feel about yourself, the less you feel the need to show off.",
"I think everybody's weird. We should all celebrate our individuality and not be embarrassed or ashamed of it.",
"You are very powerful, provided you know how powerful you are.",
"No one can make you feel inferior without your consent.",
"It ain't what they call you, it's what you answer to.",
"There are days I drop words of comfort on myself like falling leaves and remember that it is enough to be taken care of by myself.",
"Trust yourself. You know more than you think you do.",
"Because one believes in oneself, one doesn't try to convince others. Because one is content with oneself, one doesn't need others' approval. Because one accepts oneself, the whole world accepts him or her.",
"People who want the most approval get the least and the people who need approval the least get the most.",
"There is nothing noble about being superior to some other man. The true nobility is in being superior to your previous self.",
"I found in my research that the biggest reason people aren't more self-compassionate is that they are afraid they’ll become self-indulgent. They believe self-criticism is what keeps them in line. Most people have gotten it wrong because our culture says being hard on yourself is the way to be.",
"If you are insecure, guess what? The rest of the world is too. Do not overestimate the competition and underestimate yourself. You are better than you think.",
"When you stop living your life based on what others think of you real life begins. At that moment, you will finally see the door of self-acceptance opened.",
"You find peace not by rearranging the circumstances of your life, but by realizing who you are at the deepest level.",
"Growth begins when we start to accept our own weakness.",
"Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude.",
"Your task is not to seek for Love, but merely to seek and find all the barriers within yourself that you have built against it.",
"When we fulfill our function, which is to truly love ourselves and share love with others, then true happiness sets in.",
"Accept yourself, love yourself, and keep moving forward. If you want to fly, you have to give up what weighs you down.",
"Did your mom ever tell you, ‘If you can’t say something nice, don’t say anything’? She was right–and talking nicely also applies when you’re talking to yourself, even inside your head.",
"You can have anything you want if you are willing to give up the belief that you can’t have it.",
"self-love is an ocean and your heart is a vessel. Make it full, and any excess will spill over into the lives of the people you hold dear. But you must come first.",
 "Beauty begins the moment you decided to be yourself.",
"Your problem is you’re… too busy holding onto your unworthiness.",
"The reward for conformity is that everyone likes you but yourself.",
"She lacks confidence, she craves admiration insatiably. She lives on the reflections of herself in the eyes of others. She does not dare to be herself.",
"People are like stained-glass windows. They sparkle and shine when the sun is out, but when the darkness sets in their true beauty is revealed only if there is light from within.",
"If you aren't good at loving yourself, you will have a difficult time loving anyone, since you’ll resent the time and energy you give another person that you aren't even giving to yourself.",
"Most of the shadows of this life are caused by standing in one's own sunshine.",
"It's surprising how many persons go through life without ever recognizing that their feelings toward other people are largely determined by their feelings toward themselves, and if you're not comfortable within yourself, you can't be comfortable with others.",
"When I loved myself enough, I began leaving whatever wasn't healthy. This meant people, jobs, my own beliefs and habits – anything that kept me small.  My judgement called it disloyal. Now I see it as self-loving.",
 "There came a time when the risk to remain tight in the bud was more painful than the risk it took to blossom.",
"It took me a long time not to judge myself through someone else's eyes.",
"The best day of your life is the one on which you decide your life is your own. No apologies or excuses. No one to lean on, rely on, or blame. The gift is yours – it is an amazing journey – and you alone are responsible for the quality of it. This is the day your life really begins.",
"Self-pity gets you nowhere. One must have the adventurous daring to accept oneself as a bundle of possibilities and undertake the most interesting game in the world making the most of one's best.",
"It is never too late to be what you might have been.",


];



